#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/myaccounting_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=myaccounting_user
spring.datasource.password=mM@098098789