#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${STORE_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${STORE_USERNAME}
spring.datasource.password=${STORE_PASSWORD}